sudo: required
language: 
  - node_js
  - c++

node_js: "0.10"

before_install: 
  - "sudo apt-get update"
  - "bash install_deps.sh"
  - "npm install -g nodeunit"

include:
  # works on Precise and Trusty
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
    env:
      - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

dist: "artful"