platform: 
  - x32
  - x64

image: Visual Studio 2017

install:
  - ps: Install-Product node 4
  - yarn global add node-gyp
  - yarn install --ignore-scripts

build_script:
  - node-gyp rebuild

test_script:
  - cmd: yarn test