platform: 
  - x32
  - x64

install:
  - ps: Install-Product node 0.10
  - npm install
  - npm install -g nodeunit

build_script:
  - npm rebuild

test_script:
  - ps: "npm test # PowerShell"
  - cmd: npm test