platform: 
  - x32
  - x64

image: Visual Studio 2017

install:
  - ps: Install-Product node 0.10
  - npm install -g npm@3.3.3
  - npm install
  - npm install -g nodeunit

build_script:
  - npm rebuild

test_script:
  - ps: "npm test # PowerShell"
  - cmd: npm test